export default class DataManager {
    static myInstance = null; //variable to store login
    userID= "";
    screenID="";
    screenColoumn="";
    buyitem="";

    
    users = [
        {
            id: "user1",
            idNo: 1,
            name: "Gojo Satoru",
            email: "g@gmail.com",
            password: "g",
            accountbal:25000,
            image: require('../assets/users/GojoSatoru.jpg')
        },
        {
            id: "user2",
            idNo: 2,
            name: "Zero Kiryu",
            email: "zero@gmail.com",
            password: "zero12",
            accountbal:10000,
            image: require('../assets/users/ZeroKiryu.jpg'),
        },
        {
            id: "user3",
            idNo: 3,
            name: "Ryoma Echizen",
            email: "ryoma@gmail.com",
            password: "ryoma1",
            accountbal:10000,
            image: require('../assets/users/RyomaEchizen.jpg'),
        },
    ];

    myHistory = [
        {
            userid: "user1",
            historyid: 1,
            title:"TianTian",
            subtitle:"One of the most iconic landmarks",
            image:require("../assets/places/tiantian.jpg"),
        },
        {
            userid: "user1",
            historyid: 2,
            title:"K 11 Musea" ,
            subtitle:"1.2 million square feet of retail space",
            image:require("../assets/places/musea.jpg"),
        },
        {
            userid: "user2",
            historyid: 3,
            title:"LKF",
            subtitle:"Also known as Lan Kwai Fong, party area",
            image:require("../assets/places/lkf.jpg"),
        },
    ]

    Tab = [
        {
            tags: 'All',
            value: 0,
        },
        {
            tags: 'Chinese',
            value: 1,
        },
        {
            tags: 'Korean',
            value: 2,
        },
        {
            tags: 'Japanese',
            value: 3,
        },
        {
            tags: 'Indian',
            value: 4,
        },
        {
            tags: 'Pizza',
            value: 5,
        },
        {
            tags: 'Fast Food',
            value: 6,
        },
        {
            tags: 'Snack',
            value: 7,
        },
        {
            tags: 'Dessert',
            value: 8,
        },
        {
            tags: 'Bubble Tea',
            value: 9,
        },
        
    ]
    Restuarants = [
        {
            userid: "user1",
            restuarantsid: 1,
            title:"Sijie Sichuan Private Kitchen",
            subtitle:"If you find yourself piling into an elevator in a commercial building in Causeway Bay, then you’re probably on the right track. ",
            image:require("../assets/food/Sichuan/Sichuan.jpg"),
            menu1:"Crab",
            cost1:"240",
            desc1:"Crab cooking with noodles and special chinese-malayasian sauce",
            menu2:"Sichuan Pot",
            cost2:"180",
            desc2:"A Pot of heaps of chilli and chicken bites with many herbs",
            menu3:"Mapo Tofu",
            cost3:"80",
            desc3:"Mapo Tofu cooked with chilli and spice  ",
            menu4:"Chicken",
            cost4:"100",
            desc4:"Kung Pao Chicken cooked with cashew nuts",
            imageCard1:require("../assets/food/Sichuan/crab.jpg"),
            imageCard2:require("../assets/food/Sichuan/chilli.jpg"),
            imageCard3:require("../assets/food/Sichuan/tofu.jpg"),
            imageCard4:require("../assets/food/Sichuan/chicken.jpg"),
            tags:"Chinese",
            price: "$$$",
            value:1,
            details:'If you find yourself piling into an elevator in a commercial building in Causeway Bay, then you’re probably on the right track. You’ll know for sure when the aroma of palate-numbing Sichuan cuisine (which hails from southwestern China) wafts through the 10th-floor corridor. With room for no more than about 30 diners at a time, the private kitchen has a homey feel, complete with old-school metal chairs, circular tables, and retro tableware.',
        },
        {
            userid: "user2",
            restuarantsid: 2,
            title:"Duddell’s" ,
            subtitle:"A mix of fine art exhibitions and fine dining, this expansive venue",
            image:require("../assets/food/Duddell/Duddell.jpg"),
            menu1:"Egg",
            cost1:"45",
            desc1:"Special entree dish with egg",
            menu2:"Beef",
            cost2:"60",
            desc2:"Cooked medium raw beef steak with garnish",
            menu3:"Vege",
            cost3:"50",
            desc3:"Califlower and beans stir fried",
            menu4:"Oyster",
            cost4:"80",
            desc4:"Oyster cooked with hoisan sauce and placed on top of Choy Sum",
            imageCard1:require("../assets/food/Duddell/egg.jpg"),
            imageCard2:require("../assets/food/Duddell/beef.jpg"),
            imageCard3:require("../assets/food/Duddell/vege.jpg"),
            imageCard4:require("../assets/food/Duddell/oyster.jpg"),
            tags:"Chinese",
            price: "$",
            value:1,
            details:'A mix of fine art exhibitions and fine dining, this expansive venue – which also boasts a spacious terrace and elegant interiors – in Central also offers one of the best modern takes on classic Cantonese cuisine in town. ',
        },
        {
            userid: "user3",
            restuarantsid: 3,
            title:"Yan Toh Heen",
            subtitle:"The most iconic postcard view of Hong Kong’s Victoria Harbor is best seen from Kowloon, and Yan Toh Heen’s sea-level, harborside setting offers front-row views. ",
            image:require("../assets/food/YTH/YTH.jpeg"),
            menu1:"Lobster",
            cost1:"240",
            desc1:"Lobster dish divided perfected for texture and taste",
            menu2:"Fried",
            cost2:"150",
            desc2:"Fried entree with abalone and cream",
            menu3:"Dumplings",
            cost3:"100",
            desc3:"Dumplings fried with vegetables and filling",
            menu4:"Dessert",
            cost4:"60",
            desc4:"A dessert to statisfy your sweet tooth ",
            imageCard1:require("../assets/food/YTH/lob.jpg"),
            imageCard2:require("../assets/food/YTH/fried.jpg"),
            imageCard3:require("../assets/food/YTH/dumplings.jpg"),
            imageCard4:require("../assets/food/YTH/dessert.jpg"),
            tags:"Chinese",
            price: "$$$",
            value:1,
            details:'The most iconic postcard view of Hong Kong’s Victoria Harbor is best seen from Kowloon, and Yan Toh Heen’s sea-level, harborside setting offers front-row views. Although the hotel is due to be renovated this year, its flagship Chinese restaurant got its facelift a little earlier, which ensures that the well-loved restaurant remains open during the hotel’s temporary closure. Chef Yiu-fai Lau has been with the hotel since it opened, and continues to please with meticulously made Cantonese classics, such as dim sum, as well as Chinese favorites like Peking duck.',
        },
        {
            userid: "user1",
            restuarantsid: 4,
            title:"K-Roll",
            subtitle:"With three branches across Hong Kong, K-Roll has made a name for itself as a great option when you’re craving Korean for lunch.",
            image:require("../assets/food/KRoll/KRoll.jpg"),
            menu1:"Chicken",
            cost1:"150",
            desc1:"Chicken Sushi Roll with mixed ingredients and vegetables",
            menu2:"Beef",
            cost2:"80",
            desc2:"Beff Sushi Roll with mixed ingredients and vegetables",
            menu3:"Salmon",
            cost3:"170",
            desc3:"Salmon Sushi Roll with mixed ingredients and vegetables",
            menu4:"Vege",
            cost4:"80",
            desc4:"Vegetable Sushi Roll with mixed ingredients",
            imageCard1:require("../assets/food/KRoll/chicken.jpg"),
            imageCard2:require("../assets/food/KRoll/beef.jpg"),
            imageCard3:require("../assets/food/KRoll/salmon.jpg"),
            imageCard4:require("../assets/food/KRoll/vege.jpg"),

            tags:"Korean",
            price: "$$",
            value: 2,
            details:'With three branches across Hong Kong, K-Roll has made a name for itself as a great option when you’re craving Korean for lunch. Bringing the humble to gimbap (Korean-style sushi) to Hong Kong, this chain was started when a Korean expat realised her daughter’s friends preferred eating her lunch to their own. Enjoy hearty portions of classic flavours here or try the spicy tofu Korrito (so good!) We are pleased to also endorse their japchae, tteokbokki and kimchi pancake.',
        },
        {
            userid: "user2",
            restuarantsid: 5,
            title:"Sorabol Korean Restaurant",
            subtitle:"Another long-established Korean spot in Hong Kong, the Michelin-recommended Sorabol serves flavorful dishes crafted with fresh, quality ingredients.",
            image:require("../assets/food/Sorabol/Sorabol.jpg"),
            menu1:"Kimichi",
            cost1:"50",
            desc1:"Fermented cabbage with chilli and spices ",
            menu2:"Raw Bibimbap",
            cost2:"100",
            desc2:"Beef bibimbap with raw beef and egg yolk mixed with vegetables ",
            menu3:"Vegetables Bibimbap",
            cost3:"90",
            desc3:"Vegetable Bibimbap with carrots and radish and lettuce",
            menu4:"Dessert",
            cost4:"65",
            desc4:"A dessert to statisfy your sweet tooth ",
            imageCard1:require("../assets/food/Sorabol/kimichi.jpg"),
            imageCard2:require("../assets/food/Sorabol/raw.jpg"),
            imageCard3:require("../assets/food/Sorabol/vege.jpg"),
            imageCard4:require("../assets/food/Sorabol/waygu.jpg"),
            tags:"Korean",
            price: "$$",
            value:2,
            details:'Another long-established Korean spot in Hong Kong, the Michelin-recommended Sorabol serves flavorful dishes crafted with fresh, quality ingredients which are delivered straight from Korea and its own organic farm in southern China. You can choose from both marinated and non-marinated barbecue options, including sliced beef brisket, sliced prime rib eye, and pork belly with sour kimchi.',
        },
        {
            userid: "user3",
            restuarantsid: 6,
            title:"Soil to Soul",
            subtitle:"The arrival of Soil to Soul in such turbulent times is eerily comforting. Opened just two months ago in July.",
            image:require("../assets/food/SoilToSoul/SoilToSoul.jpg"),
            menu1:"Entree",
            cost1:"70",
            desc1:"Tofu entrees filled with crab",
            menu2:"Fried",
            cost2:"110",
            desc2:"Fried Chicken as an entree to warm up for the next course",
            menu3:"Vegetables",
            cost3:"100",
            desc3:"A simple vegetarian dish filled with carrots and radish",
            menu4:"Dumplings",
            cost4:"90",
            desc4:"Dumplings fried with vegetables and filling",
            imageCard1:require("../assets/food/SoilToSoul/entree.jpg"),
            imageCard2:require("../assets/food/SoilToSoul/fried.jpg"),
            imageCard3:require("../assets/food/SoilToSoul/vege.jpg"),
            imageCard4:require("../assets/food/SoilToSoul/dumpling.jpg"),
            tags:"Korean",
            price: "$$$",
            value:2,
            details:'The arrival of Soil to Soul in such turbulent times is eerily comforting. Opened just two months ago in July, Soil to Soul is a plant-based restaurant inspired by Korean temple food with Executive Chef Gu Jin Kwang at the helm. Having mastered the philosophy and techniques of monastery cooking from established Buddhist nun Woo Kwan at Korea’s Mahayeon Temple Food Cultural Center, Chef Gu Jin Kwang takes to the city for his next adventure.',
        },
        {
            userid: "user1",
            restuarantsid: 7,
            title:"Crown Super Deluxe",
            subtitle:"This 60s Tokyo-inspired teppanyaki features three teppan grills in which diners can sit around and enjoy watching chefs grilling away. ",
            image:require("../assets/food/CSD/CSD.jpg"),
            menu1:"Salmon",
            cost1:"320",
            desc1:"Samon, tuna, kingfish sashimi all in a mixed plate",
            menu2:"Beef",
            cost2:"150",
            desc2:"An entree made with medium raw beed cubes",
            menu3:"Crab",
            cost3:"280",
            desc3:"Crab cooked with clear noodles and different chillis to bring out the flavour",
            menu4:"Dessert",
            cost4:"80",
            desc4:"A dessert to statisfy your sweet tooth ",
            imageCard1:require("../assets/food/CSD/salmon.jpg"),
            imageCard2:require("../assets/food/CSD/beef.png"),
            imageCard3:require("../assets/food/CSD/crab.jpg"),
            imageCard4:require("../assets/food/CSD/dessert.jpg"),
            tags:"Japanese",
            price: "$$$$",
            value:3,
            details:'This 60s Tokyo-inspired teppanyaki features three teppan grills in which diners can sit around and enjoy watching chefs grilling away. The restaurant is helmed by Niigata native Toru Takano, and serves up an array of top-quality meat and seafood. The Deluxe set comes highly recommended and includes a flow of appetisers and grill items including sashimi, Tokushima tomato, spicy lobster, and A5 Kagoshima wagyu beef. After the main meal, diners can move into the dessert and whisky lounge, to enjoy an after-dinner tipple complemented by sweet treats.',
        },
        {
            userid: "user2",
            restuarantsid: 8,
            title:"Fukuro",
            subtitle:"This modern izakaya is helmed by chef Shun Sato, a Sendai native who has worked in Tokyo’s famous Tsukiji Market.",
            image:require("../assets/food/Fukuro/Fukuro.jpg"),
            menu1:"Entree",
            cost1:"60",
            desc1:"Surprise, this is an appealing dish towards the eyes",
            menu2:"Egg",
            cost2:"70",
            desc2:"Stir Fry noodles with a garnish of a sunnyside up egg",
            menu3:"Noodles",
            cost3:"220",
            desc3:"Stir Fry noodles with a sunnyside up egg and dill",
            menu4:"Beef",
            cost4:"200",
            desc4:"A beef sandwich skewer cooked to a perfection of medium raw",
            imageCard1:require("../assets/food/Fukuro/entree.jpg"),
            imageCard2:require("../assets/food/Fukuro/egg.jpg"),
            imageCard3:require("../assets/food/Fukuro/noodles.jpg"),
            imageCard4:require("../assets/food/Fukuro/beef.jpg"),
            tags:"Japanese",
            price: "$$$",
            value:3,
            details:'This modern izakaya is helmed by chef Shun Sato, a Sendai native who has worked in Tokyo’s famous Tsukiji Market, Sydney restaurants BlancHaru and Yoshii – and more recently here in Hong Kong – Belon and Ho Lee Fook. Signature dishes include seasonal sashimi, drunken clams, crispy caramel butter corn and the yaki undon with snow crab. In typical izakaya fashion, quality whisky highballs are the tipple of choice.',
        },
        {
            userid: "user3",
            restuarantsid: 9,
            title:"Kido",
            subtitle:"Yakitori joint Kido stays true to yakitori traditions with their cosy counter table setting and a classic menu",
            image:require("../assets/food/Kido/Kido.jpg"),
            menu1:"Entree",
            cost1:"70",
            desc1:"A special dish with diferrent skewers of sushi and fish",
            menu2:"Chicken",
            cost2:"150",
            desc2:"An entree of chicken skewers to start up your appetite",
            menu3:"Sushi",
            cost3:"130",
            desc3:"Assorted sashimi and sushi rolls",
            menu4:"Rice",
            cost4:"150",
            desc4:"A special fried rice shaped in a ball with a surprise inside",
            imageCard1:require("../assets/food/Kido/entree.jpg"),
            imageCard2:require("../assets/food/Kido/chicken.jpg"),
            imageCard3:require("../assets/food/Kido/sushi.jpg"),
            imageCard4:require("../assets/food/Kido/rice.jpg"),
            tags:"Japanese",
            price: "$$",
            value:3,
            details:'Yakitori joint Kido stays true to yakitori traditions with their cosy counter table setting and a classic menu that includes every part of the chicken. But on top of that, this yakitori skewer bar will also be serving up traditional, Fukuoka-style skewers, extending the menu to healthier, more diverse skewered dishes that include other meats, vegetables, and even fruits. Led by Kido’s head chef Kimura Junichiro, diners will be able to authentically experience the timeless tradition and culture of yakitori feasting in this trendy, classic, yet nevertheless distinctly Japanese hideout.',
        },
        {
            userid: "user1",
            restuarantsid: 10,
            title:"CHAAT",
            subtitle:"Helmed by chef Manav Tuli, previously head chef of Michelin-starred Tamarind in London",
            image:require("../assets/food/CHAAT/CHAAT.jpg"),
            menu1:"Butter Chicken",
            cost1:"140",
            desc1:"A famous indian recipe that was perfected over generations and generations ",
            menu2:"Pocket",
            cost2:"180",
            desc2:"A large baked pocket filled with mince and vegetables for the family to share",
            menu3:"Seafood",
            cost3:"170",
            desc3:"A spiced made seafood dish for those for love sashimi and their heat",
            menu4:"Dessert",
            cost4:"70",
            desc4:"A dessert to statisfy your sweet tooth after a hot and spicy meal",
            imageCard1:require("../assets/food/CHAAT/butter.jpg"),
            imageCard2:require("../assets/food/CHAAT/pocket.jpg"),
            imageCard3:require("../assets/food/CHAAT/shell.jpg"),
            imageCard4:require("../assets/food/CHAAT/dessert.jpg"),
            tags:"Indian",
            price: "$$",
            value:4,
            details:'Helmed by chef Manav Tuli, previously head chef of Michelin-starred Tamarind in London, Chaat serves up a fresh take on classic Indian street food and elevates Indian culinary favourites that are drawn from a variety of colourful flavours that transport you all across India.',
        },
        {
            userid: "user2",
            restuarantsid: 11,
            title:"New Punjab Club",
            subtitle:"New Punjab Club made headlines last year when it became the first Punjabi restaurant in the world to be awarded a Michelin star. ",
            image:require("../assets/food/NPC/NPC.png"),
            menu1:"Butter Chicken",
            cost1:"150",
            desc1:"A famous indian recipe that was perfected over generations and generations ",
            menu2:"Naan Bread",
            cost2:"125",
            desc2:"baked to a golden crunchy bread with a glistening of butter",
            menu3:"Chicken",
            cost3:"130",
            desc3:"Chicken marinated to perfection and paired with a special sauce",
            menu4:"Soup",
            cost4:"85",
            desc4:"An entree to warm your mouth up for the upcoming feast",
            imageCard1:require("../assets/food/NPC/butter.jpg"),
            imageCard2:require("../assets/food/NPC/naan.jpg"),
            imageCard3:require("../assets/food/NPC/chicken.jpg"),
            imageCard4:require("../assets/food/NPC/green.jpg"),
            tags:"Indian",
            price: "$$$",
            value:4,
            details:'New Punjab Club made headlines last year when it became the first Punjabi restaurant in the world to be awarded a Michelin star. This restaurant celebrates post-colonial Pakistan and India through rustic and uncomplicated delights. Executive chef Palash Mitra and his team also emphasise the importance of recreating Punjabi classics through locally sourced fish and meats. Favourites include the comforting samosa chaat, which is filled with potatoes and spices with the surprise of pomegranate seeds, and buttery tandoori machli that melts in your mouth.',
        },
        {
            userid: "user3",
            restuarantsid: 12,
            title:"Pondi",
            subtitle:"Tucked away at the end of Sai Ying Pun’s vibrant Fuk Sau Lane, Pondi is a delightful new addition to an already exciting alcove in this residential neighbourhood",
            image:require("../assets/food/Pondi/Pondi.jpg"),
            menu1:"French",
            cost1:"130",
            desc1:"Orginally an Indian-French entree to applease your appetite",
            menu2:"Frozen",
            cost2:"150",
            desc2:"Liquid nitrogen placed under to increase your taste",
            menu3:"Garlic",
            cost3:"125",
            desc3:"Sir Fried and placed neatly for your eyes to eat",
            menu4:"Fish",
            cost4:"180",
            desc4:"Fish cooked with home made sauce and topped with cheese and garnish",
            imageCard1:require("../assets/food/Pondi/french.jpg"),
            imageCard2:require("../assets/food/Pondi/frozen.jpg"),
            imageCard3:require("../assets/food/Pondi/garlic.jpg"),
            imageCard4:require("../assets/food/Pondi/fish.jpg"),
            tags:"Indian",
            price: "$$",
            value:4,
            details:'The space sets the scene for epicurean bliss, with a thoughtfully decked out, candlelit alfresco terrace that opens onto the street and allows diners to relax while being immersed in the buzz of the neighbourhood. Inside, the kitchen bar seating is an intimate, modern nook where diners can chat away and look on as the chefs prepare dishes behind the counter. Upstairs there’s additional seating, but only reserved for private parties of 20 or more.',
        },
        {
            userid: "user1",
            restuarantsid: 13,
            title:"Dough Bros",
            subtitle:"Located not far off the Happy Valley Racecourse, Dough Bros may be a tiny take-out pizza shop with just a few stools.",
            image:require("../assets/food/DoughBros/DoughBros.jpg"),
            menu1:"Bacon Pizza",
            cost1:"95",
            desc1:"Cooked to the crisp and placed to perfect around cherry tomatos on a slice of pizza",
            menu2:"Ham Pizza",
            cost2:"90",
            desc2:"Thinly sliced ham placed to perfect around cherry tomatos on a slice of pizza",
            menu3:"Cheese Pizza",
            cost3:"60",
            desc3:"A mix of every cheese you could think of on a pizza",
            menu4:"Spinach Pizza",
            cost4:"65",
            desc4:"A pizza filled with vegetables to the brim! Yummy Spinach",
            imageCard1:require("../assets/food/DoughBros/bacon.jpg"),
            imageCard2:require("../assets/food/DoughBros/ham.jpg"),
            imageCard3:require("../assets/food/DoughBros/cheese.jpg"),
            imageCard4:require("../assets/food/DoughBros/spinach.jpg"),
            tags:"Pizza",
            price: "$$",
            value:5,
            details:'Located not far off the Happy Valley Racecourse, Dough Bros may be a tiny take-out pizza shop with just a few stools, but their artisanal sourdough pizza and freshly-filled doughnuts (heads up, Nutella fanatics!) are certainly worth the wait. Not to mention the wide selection of local/imported beers and wines that are sure to quench your thirst as the chef hand-rolls your pizza on the spot. Good news for those who nearer to Central is that Dough Bros have recently expanded their operations to Soho.',
        },
        {
            userid: "user2",
            restuarantsid: 14,
            title:"Paisano’s",
            subtitle:"We’re not ashamed to admit that we’re fans of a cheap and cheerful slice from Paisanos following a night on the town.",
            image:require("../assets/food/Paisano/Paisano.jpg"),
            menu1:"Beef Pizza",
            cost1:"150",
            desc1:"Beef mince sprinkled over a pizza loaded with cheese and tomatos",
            menu2:"Onion Pizza",
            cost2:"110",
            desc2:"A perfectly baked pizza with onions cooked to its perfection",
            menu3:"Pepperoni Pizza",
            cost3:"130",
            desc3:"slightly smoky covered with pepperoni and cheese and spinach",
            menu4:"Mixed Pizza",
            cost4:"190",
            desc4:"A Chosen mix of the different slices of pizza you would like",
            imageCard1:require("../assets/food/Paisano/meat.jpg"),
            imageCard2:require("../assets/food/Paisano/onion.jpg"),
            imageCard3:require("../assets/food/Paisano/pep.jpg"),
            imageCard4:require("../assets/food/Paisano/mixed.jpg"),
            tags:"Pizza",
            price: "$$",
            value:5,
            details:'We’re not ashamed to admit that we’re fans of a cheap and cheerful slice from Paisanos following a night on the town. Yes, we know there are those of you who look down on Paisanos, and their claim of producing authentic New York-style pizzas. But, we do feel there is a time and a place for their huge slice of pizza pies — they’re perfect for house parties, junk parties, BBQs, and pretty damn satisfying to eat when you’ve got the drunken munchies. And, there are many outlets across the city, which means that there’s usually one within stumbling distance. Prices range from HK$25-45 per slice, and HK$100-340 for the entire pizza, according to the size and topping selection.',
        },
        {
            userid: "user3",
            restuarantsid: 15,
            title:"La Camionetta",
            subtitle:"Yet another pizzeria to grace our city, La Camionetta is a cosy Italian spot that is fronted by a vintage Volkswagen Kombi bus.",
            image:require("../assets/food/LaC/LaC.jpg"),
            menu1:"Cheese Pizza",
            cost1:"90",
            desc1:"A mix of every cheese you could think of on a pizza",
            menu2:"Mushroom Pizza",
            cost2:"100",
            desc2:"Mushroom, Tomato and feta cheese all on the a slice of pizza",
            menu3:"Hawaiian Pizzza",
            cost3:"90",
            desc3:"Pineapple onto of cheese on a pizza",
            menu4:"Pepperoni Pizza",
            cost4:"120",
            desc4:"slightly smoky covered with pepperoni and cheese and spinach",
            imageCard1:require("../assets/food/LaC/cheese.jpg"),
            imageCard2:require("../assets/food/LaC/mushroom.jpg"),
            imageCard3:require("../assets/food/LaC/haw.jpg"),
            imageCard4:require("../assets/food/LaC/pep.jpg"),
            tags:"Pizza",
            price: "$$",
            value:5,
            details:'Yet another pizzeria to grace our city, La Camionetta is a cosy Italian spot that is fronted by a vintage Volkswagen Kombi bus (hence the restaurant’s name, meaning truck in Italian) and offers handcrafted pizzas and Italian aperitivo. Though the owners are actually French, it’s the pizzas that do the work in whisking you away to Italy. The pizza bianca (white base) La CamBurrata has a crisp crust and fluffy dough topped with creamy fior di latte, cherry tomatoes, savoury Parma ham and 150g of burrata. Just cut in and let the milky, buttery burrata flow onto the pizza.',
        },
        {
            userid: "user1",
            restuarantsid: 16,
            title:"Fairwood",
            subtitle:"Fairwood is one of Hong Kong’s most popular fast food restaurant chains.",
            image:require("../assets/food/Fairwood/Fairwood.jpg"),
            menu1:"Chicken ",
            cost1:"55",
            desc1:"BBQ Chicken with rice and with vegetables",
            menu2:"Satay Beef Sandwich",
            cost2:"40",
            desc2:"Stir Fry Stay Beef with egg and butter in toast",
            menu3:"Pinapple Bun",
            cost3:"35",
            desc3:"Pineapple buns filled with melted butter that hits the spot",
            menu4:"HK Milk Tea",
            cost4:"24",
            desc4:"Hong Kong smooth milk tea made freshly ",
            imageCard1:require("../assets/food/Fairwood/chicken.jpg"),
            imageCard2:require("../assets/food/Fairwood/satay.jpg"),
            imageCard3:require("../assets/food/Fairwood/pineapple.jpg"),
            imageCard4:require("../assets/food/Fairwood/milkTea.jpg"),
            tags:"Fast Food",
            price: "$",
            value:6,
            details:'Fairwood is one of Hong Kong’s most popular fast food restaurant chains. With 137 outlets spread across Hong Kong Island, the Kowloon Peninsula, and the New Territories, the chain serves Chinese and international dishes at affordable prices in comfortable surroundings. Fairwood is a mass market restaurant chain serving a varied and rotating menu running from Cantonese style roasted meats to Chinese food, Indian curries, Japanese ramens, and Hong Kong-style Western dishes.',
        },
        {
            userid: "user2",
            restuarantsid: 17,
            title:"Café de Coral",
            subtitle:"Cafe deCoral is a fast food restuarant",
            image:require("../assets/food/Cafe/Cafe.jpg"),
            menu1:"BBQ Soy Chicken",
            cost1:"65",
            desc1:"BBQ Soy chicken with rice and vegetables",
            menu2:"BBQ Duck",
            cost2:"65",
            desc2:"BBQ duck with rice and vegetables",
            menu3:"Chicken Leg",
            cost3:"70",
            desc3:"BBQ chicken Leg with  rice ",
            menu4:"Baked Pork Chop",
            cost4:"80",
            desc4:"Baked tomato Pork Chop in cheesy fried rice",
            imageCard1:require("../assets/food/Cafe/chicken.jpg"),
            imageCard2:require("../assets/food/Cafe/duck.jpg"),
            imageCard3:require("../assets/food/Cafe/chickenLeg.jpeg"),
            imageCard4:require("../assets/food/Cafe/bakedRice.jpg"),
            tags:"Fast Food",
            price: "$",
            value:6,
            details:'Café de Coral Holdings, Ltd. (Chinese: 大家樂集團有限公司) is a fast-food restaurant group that owns and operates fast-food chains and restaurants, including Café de Coral, Super Super, The Spaghetti House, Olivers Super Sandwiches, Ah Yee Leng Tong, and others.Founded in 1968, the Café de Coral group opened its first Café de Coral restaurant in the Causeway Bay district of Hong Kong in 1969. Since then, the group has grown to operate over 580 separate outlets across its brands all over the world. It is the largest Chinese fast-food restaurant group in Hong Kong and in the world. In Hong Kong alone, it caters to over 300,000 people on a typical day.',
        },
        {
            userid: "user3",
            restuarantsid: 18,
            title:"Yoshinoya",
            subtitle:"Yoshinoya was born in 1899 under the ingenuity of its founder, a Japanese, named Eikichi Matsuda. ",
            image:require("../assets/food/Yoshinoya/Yoshinoya.jpg"),
            menu1:"Chicken",
            cost1:"80",
            desc1:"BBQ chicken with vegetables and rice",
            menu2:"Beef",
            cost2:"85",
            desc2:"Stir-Fry Beef with special sauce on rice",
            menu3:"Stir Fry",
            cost3:"95",
            desc3:"Stir-Fry Beef with rice topped with garnish of carrots and lettuce",
            menu4:"Soft Drinks",
            cost4:"15",
            desc4:"Your Choice in Soft Drinks",
            imageCard1:require("../assets/food/Yoshinoya/chicken.jpg"),
            imageCard2:require("../assets/food/Yoshinoya/beef.jpg"),
            imageCard3:require("../assets/food/Yoshinoya/stirFry.jpg"),
            imageCard4:require("../assets/food/Yoshinoya/softDrinks.jpg"),
            tags:"Fast Food",
            price: "$",
            value:6,
            details:'Yoshinoya was born in 1899 under the ingenuity of its founder, a Japanese, named Eikichi Matsuda. Our story begins at Nihonbashi, a humble fish market in Chuo-ku, Tokyo, on the outskirts of Edo Castle where Mr. Matsuda created a delicious recipe of beef and rice known as Gyudon (beef bowl). Named for his birthplace of Yoshino-Cho, Osaka, Mr. Matsuda’s restaurant featured delicious, affordable and fast meals. It was an entirely new concept in Japanese culture, and both the hard-working fisherman and market visitors embraced it. Yoshinoya was an instant hit. In 1923, Japan was hit by the Great Kanto Earthquake and Yoshinoya had to move to Tsukiji with the rest of the fish market and throngs of hungry patrons continued to enjoy Yoshinoya’s original gyūdon, or Beef Bowl.',
        },
        {
            userid: "user1",
            restuarantsid: 19,
            title:"Hop Yik Tai",
            subtitle:"Michelin recommended local restaurant in Sham Shui Po that specialises in cheong fun.",
            image:require("../assets/food/HYT/HYT.jpg"),
            menu1:"Siu Mai",
            cost1:"25",
            desc1:"Siu Mai is a popular yum cha item but is also a famous Hong Kong street food, ",            
            menu2:"Cheung Fun",
            cost2:"25",
            desc2:"Rice paper steamed rolls, covered with hoison sauce and chill sauce",
            menu3:"Curry Fish Balls",
            cost3:"25",
            desc3:"Curry fish balls is a famous Hong Kong street food, with many different levels of spice",
            menu4:"Soft Drinks",
            cost4:"15",
            desc4: "Your choice in Soft Drinks",
            imageCard1:require("../assets/food/HYT/siu.png"),
            imageCard2:require("../assets/food/HYT/fun.jpg"),
            imageCard3:require("../assets/food/HYT/curry.png"),
            imageCard4:require("../assets/food/HYT/softDrinks.jpg"),
            tags:"Snack",
            price: "$$",
            value:7,
            details:'Michelin recommended local restaurant in Sham Shui Po that specialises in cheong fun. Sham Shui Po has no shortage of mouth-watering street food but Hop Yik Tai’s cheong fun, or rice noodle rolls, are worth crossing the harbour for. Made fresh every day, their cheong fun is incredibly smooth and paired perfectly with sweet sauce, sesame sauce and soy sauce. It’s no wonder why there are queues all the time. The popular local eatery was also recommended in the Michelin Guide last year.',
        },
        {
            userid: "user2",
            restuarantsid: 20,
            title:"More Eggettes",
            subtitle:"With its innovation and love for egg waffles, Street Egg Waffles has changed its name to Moya Egg Waffles.",
            image:require("../assets/food/Eggettes/Eggettes.jpg"),
            menu1:"Eggettes",
            cost1:"20",
            desc1:"The original egg waffle shaped like an egg",
            menu2:"Egg Waffles",
            cost2:"25",
            desc2:"Waffles filled with peanut butter, condensed milk and a sprinkle of sugar",
            menu3:"Chocolate",
            cost3:"35",
            desc3:"The egg waffle shaped like an egg, covered with Chocolate and cream",
            menu4:"Strawberry",
            cost4:"35",
            desc4:"The egg waffle shaped like an egg, covered with Strawberry and cream",
            imageCard1:require("../assets/food/Eggettes/egg.jpg"),
            imageCard2:require("../assets/food/Eggettes/waffle.jpg"),
            imageCard3:require("../assets/food/Eggettes/choco.jpg"),
            imageCard4:require("../assets/food/Eggettes/straw.jpg"),
            tags:"Snack",
            price: "$$",
            value:7,
            details:'With its innovation and love for egg waffles, Street Egg Waffles has changed its name to Moya Egg Waffles, and will continue to introduce new and exciting egg waffles! We also bring new and interesting egg waffles into your banquet party, so that guests have a special memory!',
        },
        {
            userid: "user3",
            restuarantsid: 21,
            title:"Wah Kee Snack",
            subtitle:"Wah Kee Snacks at the corner of Prat and Hart Avenue in Kowloon.",
            image:require("../assets/food/WKS/WKS.jpg"),
            menu1:"BBQ Squid",
            cost1:"35",
            desc1:"BBQ Squid is a famous Hong Kong street food",
            menu2:"Stinky Tofu",
            cost2:"25",
            desc2:"Stinky Tofu is a famous Hong Kong street food, only for those who can handle the taste ",
            menu3:"Siu Mai",
            cost3:"30",
            desc3:"Siu Mai is a popular yum cha item but is also a famous Hong Kong street food, ",            
            menu4:"Fish Curry Balls",
            cost4:"30",
            desc4:"Curry fish balls is a famous Hong Kong street food, with many different levels of spice",
            imageCard1:require("../assets/food/WKS/squid.jpg"),
            imageCard2:require("../assets/food/WKS/tofu.jpg"),
            imageCard3:require("../assets/food/WKS/sui.jpg"),
            imageCard4:require("../assets/food/WKS/curry.jpg"),
            tags:"Snack",
            price: "$$",
            value:7,
            details:'Wah Kee Snacks at the corner of Prat and Hart Avenue in Kowloon. It is pretty popular as there are a number of pubs and KTVs around the area and was pretty crowded at night. There is a wide variety of food items to choose from, you will be addicted to their sauce.  They offer anything from fish balls, chicken wings, chicken/beef on a skewer, gizzard, octopus tentacles, pigs intestines, chicken soft bone, tofu etc and the list goes on. Might be the sauce that they served, or the crowd standing by the street chomping down the food that made the skewers of meat extra tasty, curry fish balls and deep fried intestines are my favourites.',
        },
        {
            userid: "user1",
            restuarantsid: 22,
            title:"Yee Shun Milk Company",
            subtitle:"The steamed milk pudding is also called as Shuang Pi Nai in Hong Kong.",
            image:require("../assets/food/YSMC/YSMC.jpg"),
            menu1:"Coconut Milk Pudding",
            cost1:"60",
            desc1:"Hong Kong styled steamed milk pudding within a coconut is a popular dessert",
            menu2:"Milk Pudding",
            cost2:"35",
            desc2:"Hong Kong styled steamed milk pudding is a popular dessert",
            menu3:"Egg Pudding",
            cost3:"35",
            desc3:"Hong Kong styled steamed egg pudding is a popular dessert",
            menu4:"VitaSoy Milk",
            cost4:"40",
            desc4:"Is a really yummy soy milk made with nutrious health benefits",
            imageCard1:require("../assets/food/YSMC/coco.jpg"),
            imageCard2:require("../assets/food/YSMC/milk.jpg"),
            imageCard3:require("../assets/food/YSMC/egg.png"),
            imageCard4:require("../assets/food/YSMC/vitasoy.jpg"),
            tags:"Dessert",
            price: "$$",
            value:8,
            details:'The steamed milk pudding is also called as Shuang Pi Nai in Hong Kong. It is of the combination of milk, sugar and egg. While the ingredients are very simple, the preparation of this dish really remains an arduous act. After undergoing a distinct steaming process, the result is soft smooth milk pudding with a hint of sweetness. If you want to add more sweetness, then a side of red bean with your milk pudding is worth a shot. The steamed milk pudding is perfect desserts in Hong Kong for all seasons as it is available in both hot and cold options.',
        },
        {
            userid: "user2",
            restuarantsid: 23,
            title:"Honeymoon Desserts",
            subtitle:"Durian addicts get their fix here with Honeymoon's famous durian ",
            image:require("../assets/food/Honeymoon/Honeymoon.jpg"),
            menu1:"Mango Sago",
            cost1:"30",
            desc1:"Mango Sago is a refreshing and satisfying summer dessert, with juicy chunks of mango",
            menu2:"Red Bean",
            cost2:"25",
            desc2:"Is a thick, sweet and studded with tiny ever so slightly chewy, clear tapioca pearls ",
            menu3:"Grass Jelly",
            cost3:"35",
            desc3:"Grass Jelly is a sweet dessert, popular in Hong Kong and all over Asia",
            menu4:"Bingsu",
            cost4:"55",
            desc4: "Crushed Ice with sweet flavoring and fruits, is an amazing treat during the summer",
            imageCard1:require("../assets/food/Honeymoon/mango.jpg"),
            imageCard2:require("../assets/food/Honeymoon/redBean.jpg"),
            imageCard3:require("../assets/food/Honeymoon/herbal.jpg"),
            imageCard4:require("../assets/food/Honeymoon/bingsu.jpg"),
            tags:"Dessert",
            price: "$$",
            value:8,
            details:'Durian addicts get their fix here with Honeymoons famous durian pancake – soft green skin wrapped around a thick layer of whipped cream with a chunky durian filling. If youre not a fan of the fragrant fruit, try its range of traditional sweet soup which features all the classics like red bean soup, almond tea, and sesame soup. You also cant go wrong with its mango sago pomelo pudding.',
        },
        {
            userid: "user3",
            restuarantsid: 24,
            title:"Le Bread Lab",
            subtitle:"Popular Seoul-based bakery Le Bread Lab is best known for its assortment of cutesy cakes and sweets. ",
            image:require("../assets/food/LBL/LBL.jpg"),
            menu1:"Garlic Bread with Cream",
            cost1:"38",
            desc1:"Tis bread is so rich and creamy but will leave you wanting more",
            menu2:"Soft Bread",
            cost2:"20",
            desc2:"Freshly baked bread, made extremely soft and with a nice texture",
            menu3:"Green Tea",
            cost3:"30",
            desc3: "A noticable flavor of rich green tea within layers of vanilla cake",
            menu4:"Cookies and Cream",
            cost4:"30",
            desc4:"This Oreo Cookies and Cream Layer Cake is layers of moist vanilla cake loaded with crush oreos.",
            imageCard1:require("../assets/food/LBL/garlic.jpg"),
            imageCard2:require("../assets/food/LBL/normal.jpg"),
            imageCard3:require("../assets/food/LBL/green.jpg"),
            imageCard4:require("../assets/food/LBL/cookies.jpg"),
            tags:"Dessert",
            price: "$$",
            value:8,
            details:'Popular Seoul-based bakery Le Bread Lab is best known for its assortment of cutesy cakes and sweets. Wrap your lips around the signature strawberry omelette – a small, folded cake topped with cream, strawberry, and icing sugar – or try its newer omelette creations filled with mango, banana, or chocolate. Whichever you choose, be sure to pair it with a cup of strawberry latte or milk tea.',
        },
        {
            userid: "user1",
            restuarantsid: 25,
            title:"Ten Ren’s Tea",
            subtitle:"Despite having been in the bubble tea scene for a while, Ten Ren’s Tea has not lost its charm and popularity with locals.",
            image:require("../assets/food/TRT/TRT.png"),
            menu1:"Red Bean",
            cost1:"30",
            desc1:"Red Bean, also known as adzuki bean, is a topping made from dried red beans and sugar.",
            menu2:"Taro",
            cost2:"30",
            desc2:"Taro milk tea is typically a boba milk tea that is flavoured with taro. It has a sweet and vanilla flavor.",
            menu3:"Fruit Tea",
            cost3:"26",
            desc3:"Fruit Teas are black teas flavoured with a natural essence of fruit.",
            menu4:"Brown Sugar",
            cost4:"35",
            desc4:"Brown Sugar Boba Milk Tea, this confectionery drink originated from Taiwan",
            imageCard1:require("../assets/food/TRT/red.jpg"),
            imageCard2:require("../assets/food/TRT/taro.jpg"),
            imageCard3:require("../assets/food/TRT/fruit.jpg"),
            imageCard4:require("../assets/food/TRT/brown.jpg"),
            tags:"Bubble Tea",
            price: "$",
            value:9,
            details:'Despite having been in the bubble tea scene for a while, Ten Ren’s Tea has not lost its charm and popularity with locals. Why? Because Ten Ren has a huge variety of tea-based beverages to choose from, without sacrificing its original tea flavours. Signatures like the 913 King’s oolong tea, pu’er tea latte, orange green tea, and bubble green milk tea are a safe bet if you dont know what to have, but be sure to leave room for their tea-flavoured ice creams, too.',
        },
        {
            userid: "user2",
            restuarantsid: 26,
            title:"Milksha",
            subtitle:"Those who prefer their bubble tea milky should make a beeline for Milksha.",
            image:require("../assets/food/Milksha/Milksha.jpg"),
            menu1:"Green Tea",
            cost1:"28",
            desc1:"Green tea is one of the most popular flavors of bubble tea.",
            menu2:"Milk Tea",
            cost2:"25",
            desc2:"Bubble tea tastes like a well balanced and sweet milky beverage with a slight twist, boba pearls.",
            menu3:"Brown Sugar",
            cost3:"35",
            desc3:"Brown Sugar Boba Milk Tea, this confectionery drink originated from Taiwan",
            menu4:"Taro",
            cost4:"35",
            desc4:"Taro milk tea is typically a boba milk tea that is flavoured with taro. It has a sweet and vanilla flavor.",
            imageCard1:require("../assets/food/Milksha/green.jpg"),
            imageCard2:require("../assets/food/Milksha/white.jpg"),
            imageCard3:require("../assets/food/Milksha/brown.jpg"),
            imageCard4:require("../assets/food/Milksha/taro.jpeg"),
            tags:"Bubble Tea",
            price: "$",
            value:9,
            details:'Those who prefer their bubble tea milky should make a beeline for Milksha. The beverages here are served with fresh milk procured from Milkshas own pastures in Taiwan. One downside is that the portions here arent too large – cups are about the size of your palm – but the flavours more than make up for it. We recommend going for the taro milk tea, puer bubble milk tea, and the brown sugar milk tea.',
        },
        {
            userid: "user3",
            restuarantsid: 27,
            title:"Jen Ju Dan",
            subtitle:"The attention to detail is what makes Jen Ju Dan appealing to bubble tea lovers.",
            image:require("../assets/food/JJD/JJD.jpg"),
            menu1:"Brown Sugar",
            cost1:"35",
            desc1:"Brown Sugar Boba Milk Tea, this confectionery drink originated from Taiwan",
            menu2:"Cookies",
            cost2:"40",
            desc2:"Cookies and cream frothy yet creamy with the texture of tapioca balls.",
            menu3:"Fruit Tea",
            cost3:"25",
            desc3:"Fruit Teas are black teas flavoured with a natural essence of fruit.",
            menu4:"Taro",
            cost4:"30",
            desc4:"Taro milk tea is typically a boba milk tea that is flavoured with taro. It has a sweet and vanilla flavor.",
            imageCard1:require("../assets/food/JJD/brown.jpg"),
            imageCard2:require("../assets/food/JJD/cookies.jpg"),
            imageCard3:require("../assets/food/JJD/fruit.jpg"),
            imageCard4:require("../assets/food/JJD/taro.jpg"),
            tags:"Bubble Tea",
            price: "$",
            value:9,
            details:'The attention to detail is what makes Jen Ju Dan appealing to bubble tea lovers. If you’re particular about the pearls in your drink, youll be happy to know that Jen Ju Dan is renowned for the meticulous cooking process of its pearls. Soaked and cooked in brown sugar, each chewy little ball acts as a natural sweetener to the drinks. Crowd favourites include the fresh milk with brown sugar and pudding, the oolong latte, the Thai milk tea, and the honey lemon chrysanthemum tea.',
        },
    ]

    Categories = [
    ]

    Hotels = [
        {
            id: '1',
            name: 'Langham Hotel',
            location: 'Tsim Sha Tsui',
            price: '450',
            cost: 400,
            image1: require('../assets/stay/Langham/Langham1.jpg'),
            image2: require('../assets/stay/Langham/Langham2.jpg'),
            image3: require('../assets/stay/Langham/Langham3.jpg'),
            image4: require('../assets/stay/Langham/Langham4.jpg'),
            image5: require('../assets/stay/Langham/Langham5.jpg'),
            image6: require('../assets/stay/Langham/Langham6.jpg'),
            image7: require('../assets/stay/Langham/Langham7.jpg'),
            blurb: 'The dining options at The Langham are so good that you’ll likely never want to leave.  ',
            details: `Revamped in 2014, the rooms seem designed with Audrey Hepburn in mind—fresh yet classic, complete with a chaise lounge by the windows and black-and-white fashion portraits above the bed. While the entry-level rooms are a bit snug (about 320 square feet), they expand considerably at the Executive Room level. The suites are marvelous—each featuring its own design. The dining options at The Langham are so good that you’ll likely never want to leave. Standouts are the afternoon tea service at Palm Court, drinks at Artesian Bar (also in the lobby lounge), and three-Michelin-starred T’ang Court. The deep crimson drapes, white tablecloths, and understated gold accents at T’ang evoke a lavish Chinese mansion. Elsewhere in the building, The Bostonian Seafood & Grill serves up surf ‘n’ turf, while Main St. Deli specializes in all things New York-style deli: milkshakes, cheesecake, burgers, and sandwiches like a hearty Reuben.`,
          },
          {
            id: '2',
            name: 'Cordis',
            location: 'Mong Kok',
            price: '320',
            cost: 320,
            image1: require('../assets/stay/Cordis/Cordis1.jpg'),
            image2: require('../assets/stay/Cordis/Cordis2.jpg'),
            image3: require('../assets/stay/Cordis/Cordis3.jpg'),
            image4: require('../assets/stay/Cordis/Cordis4.jpg'),
            image5: require('../assets/stay/Cordis/Cordis5.jpg'),
            image6: require('../assets/stay/Cordis/Cordis6.jpg'),
            image7: require('../assets/stay/Cordis/Cordis7.jpg'),
            blurb:'A tech-savvy hotel, Cordis equips rooms with a free-to-use smartphone which can be used as Wi-fi ',
            details: `Clean-cut and contemporary, the 665 rooms and suites make a great first impression with fresh white linens, wooden headboards, and sumptuous leather. We booked a Club Deluxe on an upper floor and were immediately drawn to the windows. The view overlooks the incredibly densely packed cityscape There’s a working desk right next to the window, which means you’ll have natural light all day should you be stuck answering emails. A tech-savvy hotel, Cordis equips rooms with a free-to-use smartphone which can be used as Wi-fi hotspot for your own mobile, an electric safe, and 40-inch Samsung LED TV. Even more exciting? The mini bar. Instead of the usual, this little fridge was stocked with premium snacks like Cambodian dried mangoes and black truffle chips.
            `,
          },
          {
            id: '3',
            name: 'The Fleming',
            location: 'Wan Chai',
            price: '300',
            cost: 300,
            image1: require('../assets/stay/Fleming/Fleming1.jpg'),
            image2: require('../assets/stay/Fleming/Fleming2.jpg'),
            image3: require('../assets/stay/Fleming/Fleming3.jpg'),
            image4: require('../assets/stay/Fleming/Fleming4.jpg'),
            image5: require('../assets/stay/Fleming/Fleming5.jpg'),
            image6: require('../assets/stay/Fleming/Fleming6.jpg'),
            image7: require('../assets/stay/Fleming/Fleming7.jpg'),
            blurb:'The impression actually begins outside, with a glimpse of the hotel’s striking retro neon sign. ',
            details: `The impression actually begins outside, with a glimpse of the hotel’s striking retro neon sign. Formerly a staid business hotel, the Fleming is fresh off a dramatic high-design makeover inspired by Hong Kong’s famous Star Ferry. A bright red elevator that feels like the hull of a boat transports guests to a nautical lobby anchored by a wall of vintage Hong Kong mailboxes.`,
          },
          {
            id: '4',
            name: 'Hotel Icon',
            location: 'Tsim Sha Tsui',
            price: '180',
            cost: 180,
            image1: require('../assets/stay/IconHotel/Icon1.jpg'),
            image2: require('../assets/stay/IconHotel/Icon2.jpg'),
            image3: require('../assets/stay/IconHotel/Icon3.jpg'),
            image4: require('../assets/stay/IconHotel/Icon4.jpg'),
            image5: require('../assets/stay/IconHotel/Icon5.jpg'),
            image6: require('../assets/stay/IconHotel/Icon6.jpg'),
            image7: require('../assets/stay/IconHotel/Icon7.jpg'),
            blurb:'The look here is stylish eco, anchored by the tallest vertical garden on the continent,',
            details: `The look here is stylish eco, anchored by the tallest vertical garden on the continent, which towers over Green café, soaking up natural light from the triple-height lobby. Creative professionals populate the café as well the outdoor pool, which appears to spill into Victoria Harbor. While you're there, be sure to dine at least once at top-floor Above & Beyond Cantonese restaurant, where you'll have excellent harbor views. We’d recommend visiting the restaurant for dim sum or a Cantonese-inspired afternoon tea, which will surprise you with an array of dynamic flavors and textures.
            `,
        },
          {
            id: '5',
            name: 'InterContinental',
            location: 'Tsim Sha Tsui',
            price: '250',
            cost: 250,
            image1: require('../assets/stay/InterContinental/InterContinental1.jpg'),
            image2: require('../assets/stay/InterContinental/InterContinental2.jpg'),
            image3: require('../assets/stay/InterContinental/InterContinental3.jpg'),
            image4: require('../assets/stay/InterContinental/InterContinental4.jpg'),
            image5: require('../assets/stay/InterContinental/InterContinental5.jpg'),
            image6: require('../assets/stay/InterContinental/InterContinental6.jpg'),
            image7: require('../assets/stay/InterContinental/InterContinental7.jpg'),
            blurb:'A sprawling piazza with a “feng shui” fountain marks the entrance to the InterContinental Hong Kong',
            details: `Be sure to take a dip in the harborfront infinity spa pools (with a series of three-temperature hot tubs) and schedule a spa or exercise session at I-Spa. Decked in soothing green granite, the space has five spa suites—each kitted out with a private steam shower and Jacuzzi. The I-Spa team also organizes wellness experiences throughout the week for in-house guests, including complimentary tai chi classes five mornings a week, and complimentary yoga and Pilates on weekends. If you happen to be visiting over New Year’s Eve, Chinese New Year (usually in January or February) or Chinese National Day (October 1), this is the top spot to catch Hong Kong’s famous fireworks shows.`,
        },
          {
            id: '6',
            name: 'The Mira',
            location: 'Tsim Sha Tsui',
            price: '280',
            cost: 280,
            image1: require('../assets/stay/Mira/Mira1.jpg'),
            image2: require('../assets/stay/Mira/Mira2.jpg'),
            image3: require('../assets/stay/Mira/Mira3.jpg'),
            image4: require('../assets/stay/Mira/Mira4.jpg'),
            image5: require('../assets/stay/Mira/Mira5.jpg'),
            image6: require('../assets/stay/Mira/Mira6.jpg'),
            image7: require('../assets/stay/Mira/Mira7.jpg'),
            blurb:'Walking into The Mira’s minimalist lobby feels like entering another galaxy',
            details: `Walking into The Mira’s minimalist lobby feels like entering another galaxy—one light years away from the crowded Tsim Sha Tsui streets outside. Wavy white walls and reflective space-black ceilings give the place a club feel. The Mira is home to a few standout bars and restaurants, including Michelin-recommended Cuisine Cuisine. A testament to the high-quality ingredients and time-honored dishes, the Cantonese dim sum spot fills up quickly with local diners during lunch hour. Favorites include the truffle mushroom dumplings, golden har gow (topped with gold leaf), palate-cleansing cucumbers with garlic and vinegar sauce, and the shimmering egg custard and purple sweet potato buns (topped with edible shimmer dust). To feed a bigger party, go all out with a signature char siu (barbecue pork belly) or a Peking duck, which is roasted with lychee wood and served with colorful pancakes. In addition to excellent dim sum, The Mira also counts a few more must-visit F&B spots under its roof including alfresco Vibes, a secret garden-esque lounge-bar, Whisk for contemporary western cuisine, and massive Yamm buffet.
            `,
        },        {
            id: '7',
            name: 'The Murray',
            location: 'Central',
            price: '180',
            cost: 180,
            image1: require('../assets/stay/Murray/Murray1.jpg'),
            image2: require('../assets/stay/Murray/Murray2.jpg'),
            image3: require('../assets/stay/Murray/Murray3.jpg'),
            image4: require('../assets/stay/Murray/Murray4.jpg'),
            image5: require('../assets/stay/Murray/Murray5.png'),
            image6: require('../assets/stay/Murray/Murray6.jpg'),
            image7: require('../assets/stay/Murray/Murray7.jpg'),
            blurb:'Dining at The Murray might be the highlight of your stay. A splashy rooftop restaurant and bar',
            details: `Dining at The Murray might be the highlight of your stay. A splashy rooftop restaurant and bar called Popinjays serves epicurean bites; Murray Lane, a Wall Street-inspired bar, slings cocktails; Garden Lounge offers a glamorous afternoon tea; Tai Pan specializes in modern European fare; and Guo Fu Lou delivers refined Cantonese cuisine in a garden-like setting. There's also an impressive lineup of wellness offerings: A serene spa with five treatment suites, an indoor lap pool, and a 24-hour gym.`,
        },
          {
            id: '8',
            name: 'The Penisula Hotel',
            location: 'Tsim Sha Tsui',
            price: '500',
            cost: 500,
            image1: require('../assets/stay/Penisula/Penisula1.jpg'),
            image2: require('../assets/stay/Penisula/Penisula2.jpg'),
            image3: require('../assets/stay/Penisula/Penisula3.jpg'),
            image4: require('../assets/stay/Penisula/Penisula4.jpg'),
            image5: require('../assets/stay/Penisula/Penisula5.jpg'),
            image6: require('../assets/stay/Penisula/Penisula6.jpg'),
            image7: require('../assets/stay/Penisula/Penisula7.jpg'),
            blurb:'This is a dining destination that draws both travelers and locals alike with amazing scenery and a ',
            details: `This is a dining destination that draws both travelers and locals alike. The hotel’s lobby has a destination for afternoon tea—a not-to-miss experience no matter where you’re staying in Hong Kong. Guests can make a reservation and skip the queue. Elsewhere, there’s classic French restaurant Gaddi’s, avant-garde bar and restaurant Felix, Swiss cuisine at Chesa, and delicious, authentic Cantonese at Michelin-starred Spring Moon. The 12,000-square-foot Peninsula Spa is an indisputable star and a sanctuary of serenity in buzzing Hong Kong. The relaxing heat facilities are reason enough to visit— try the dry sauna overlooking Victoria Harbour and the crystal steam room. On the same floor lies an indoor pool (designed like a Roman bath house with columns and friezes), as well as an outdoor terrace and fitness center. Those traveling with children will appreciate the junior guest amenities, which include complimentary cots, child- or baby-sized bathrobes, gentle shower products, teething rings, toothbrushes, kids' menus, in-room entertainment (like movies and coloring books), and babysitting.`,
         },        {
            id: '9',
            name: 'Tuve',
            location: 'Causeway Bay',
            price: '200',
            cost: 200,
            image1: require('../assets/stay/Tuve/Tuve1.jpg'),
            image2: require('../assets/stay/Tuve/Tuve2.jpg'),
            image3: require('../assets/stay/Tuve/Tuve3.jpg'),
            image4: require('../assets/stay/Tuve/Tuve4.jpg'),
            image5: require('../assets/stay/Tuve/Tuve5.jpg'),
            image6: require('../assets/stay/Tuve/Tuve6.jpg'),
            image7: require('../assets/stay/Tuve/Tuve7.jpg'),
            blurb:'Marked by black steel doors, the narrow entrance to TUVE is so moody and dark',
            details: `Marked by black steel doors, the narrow entrance to TUVE is so moody and dark that entering feels like sneaking into a secret lair. The sparse decor—open concrete reception area, perforated metal wall, slivers of light—will feel cold to some, cool and futuristic to others.`,
         },
    ]

    Airbnb = [
        {
            id: '1',
            name: 'Stunning Large Studio',
            location: 'Hong Kong Island',
            price: '720',
            cost: 720,
            image1: require('../assets/stay/Airbnb/Studio/Studio1.jpg'),
            image2: require('../assets/stay/Airbnb/Studio/Studio2.jpg'),
            image3: require('../assets/stay/Airbnb/Studio/Studio3.jpg'),
            image4: require('../assets/stay/Airbnb/Studio/Studio4.jpg'),
            blurb: "This open and spacious studio comes with its very own private terrace",
            details: "A rare hidden gem in the heart of the city! Modern, bright, and spacious - this beautiful apartment comes with a large private terrace, and has everything you need for the most incredible stay. Perfect for family holidays, friends vacays, and business trips alike. Nestled in THE coolest neighbourhood - Sheung Wan, with delicious local diners and award-winning coffee houses at your doorstep. 1 min walk to MTR, 3 min to Central & Soho, 10 min to the peak hike trail, 20 min cab ride to the beach!",
          },
          {
            id: '2',
            name: 'Entire apartment hosted by Scott',
            location: 'Hong Kong, New Territories',
            price: '1340',
            cost: 1340,
            image1: require('../assets/stay/Airbnb/Apartment/Apartment1.jpg'),
            image2: require('../assets/stay/Airbnb/Apartment/Apartment2.jpg'),
            image3: require('../assets/stay/Airbnb/Apartment/Apartment3.jpg'),
            image4: require('../assets/stay/Airbnb/Apartment/Apartment4.jpg'),
            blurb: "You will have full access to the flat and the rooftop",
            details: "Welcome to our 550sqft 1 bedroom, 1 kitchen, living-dining 2nd floor flat with a 550sqft rooftop with a gorgeous seaview and gas BBQ facilities. Fully furnished: Double bed, sofa, washing machine, dishwasher, fridge, induction cooker, free wifi, calm and peaceful vibe. 2 people max, pets not allowed, no smoking. Convenient location in Tong Fuk within 5 minutes walk to the beach.",
          },
          {
            id: '3',
            name: 'Spacious 2 Bedroom Apartment ',
            location: 'Hong Kong Island',
            price: '570',
            cost: 570,
            image1: require('../assets/stay/Airbnb/Bedroom/Bedroom1.jpg'),
            image2: require('../assets/stay/Airbnb/Bedroom/Bedroom2.jpg'),
            image3: require('../assets/stay/Airbnb/Bedroom/Bedroom3.jpg'),
            image4: require('../assets/stay/Airbnb/Bedroom/Bedroom4.jpg'),
            blurb: "Newly renovated and furnished 2 bedroom apartment. Conveniently located and very quiet",
            details: "Welcome to my apartment, 2BR newly renovated and furnished. Located in the heart of Hong Kong's shopping, food and culture center. 2 minute walk to TST MTR station, airport transfer and all major transport. My place is close to the city center, parks, center of performing arts and culture. You’ll love my place because of the location, the people, the ambiance, and the neighborhood.",
          },
    ]
   
    
    Explore = [
        {
            userid: "user1",
            exploreid: 1,
            title:"TianTian",
            subtitle:'Also known as ‘The Big Buddha,’ Tian Tan is a large bronze statue situated next to the remote Po Lin Monastery on Lantau Island',
            image:require("../assets/places/tiantian.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:'The statue sits 34 meters high and faces the north, overlooking the Chinese people, with features that bring a depth of character to its massive form. The facial features were inspired by that of the Buddha Vairocana of the Longmen Caves, while the clothes were modeled after the Buddha Sakyamuni in Cave 360 of the Dunhuang Grottoes. The final creation holds characteristics of serene beauty and soft, flowing lines – depicting ultimate tranquility.',
        },
        {
            userid: "user1",
            exploreid: 2,
            title:"Walk of Fame",
            subtitle:'The Avenue of Stars is a 400-metre long bridge section of waterside promenade along the northern side of Victoria Harbour at Tsim Sha Tsui',
            image:require("../assets/places/bruceLee.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:'The attraction contained 73 handprints, increasing to 107 by the time of closure for renovation. Following its renovation addition these 107 handprints, nine new handprints from the winners of Hong Kong Film Award for Best Actress are to be added in the near future. All handprints have been newly designed and carry the elegant bronze colour of the Hong Kong Film Award statuette. Some of the stars more familiar to audiences outside Hong Kong include Michelle Yeoh, Jackie Chan, Bruce Lee, Jet Li, Chow Yun-fat and Maggie Cheung. Many of the stars featured are deceased. The handprints have been finely crafted and the palm prints are clearly visible. ',
        },
        {
            userid: "user1",
            exploreid: 3,
            title:"Victoria Peak",
            subtitle:"The top of Victoria Peak offers Hong Kong's most spectacular viewpoint",
            image:require("../assets/places/victoria.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:"Hong Kong is a vibrant city. One of the best experiences is to view this compact city from the top of Victoria Peak. The view is spectacular by both day and night. The peak is serviced by the Peak Tram accessible from Central MTR station. The Peak Tram, however, is not accessible to people using a wheelchair independently. The alternative way to the top is via bus 15 from either the Star Ferry Terminal at Central or the Central Bus Exchange. Each bus has one wheelchair accessible position.",
        },
        {
            userid: "user1",
            exploreid: 4,
            title:"Lady's Market",
            subtitle:"Ladies' Market is a popular place to shop for affordable fashion goods in Hong Kong",
            image:require("../assets/places/ladiesMarket.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:"Ladies' Market in Mongkok is always a treat to visit with the rows of open stalls as well as tiny boutiques offering a wide range of different fashions, accessories, gadgets and gimicks.  Frequented as much by Hongkongers as by tourists it maintains a special place in the heart of every lady, and quite a few gents, in HK.  From tourist souvineers like place name boards through travel essentials such as luggage there is always something to see and browse. We never leave the street empty-handed even if we go there just for a look!",
        },
        {
            userid: "user1",
            exploreid: 5,
            title:"K 11 Musea",
            subtitle:"K11 MUSEA is an innovative retail destination that offers public and cultural spaces alongside the shopping experience",
            image:require("../assets/places/musea.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:"K11 MUSEA is the new cultural-retail destination on Victoria Dockside, Hong Kong. Inspired by ‘A Muse by the Sea’, K11 MUSEA is designed to enrich the new consumer’s daily life through the power of creativity, culture and innovation. After 10 years of planning and building, K11 MUSEA opened its doors in August 2019 to usher in a new era of cultural retail which speaks to the growing consumer demand for naturally immersive experiences of art, culture, nature and commerce.",
        },
        {
            userid: "user1",
            exploreid: 6,
            title:"Harbour City",
            subtitle:'Harbour City is the largest and most diverse shopping mall in Hong Kong',
            image:require("../assets/places/harbourCity.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:"Harbour City is the largest and most diverse shopping mall in Hong Kong. Located at the heart of the city alongside the beautiful Victoria Harbour, Harbour City offers a wide range of shopping, dining, entertainment and sightseeing options as a major attraction in Hong Kong. Harbour City is a one-stop shopping paradise with over 450 shops, 70 food & beverage outlets, an art gallery, an observatory deck, two hotels and a cruise terminal all under one roof. With the Star Ferry Pier, it is home to cruise liner berths, maritime history and fabulous harbour view – all at its doorstep. It is easy to see where the mall drew inspiration for its name.",
        },
        {
            userid: "user1",
            exploreid: 7,
            title:"LKF",
            subtitle:'Lan Kwai Fong used to be a bustling area full of locals and tourists alike',
            image:require("../assets/places/lkf.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:"One of Hong Kong’s most popular dining, entertainment, and nightlife destinations, Lan Kwai Fong has the highest concentration of watering holes in the city: more than 100 restaurants, bars, and clubs are all crammed into just a few blocks. Conveniently located in Central, it’s where expats, locals, and visitors go to eat, drink, and be merry.",
        },
        {
            userid: "user1",
            exploreid: 8,
            title:"Temple Street Night Market",
            subtitle:'Temple Street is a street market that many tourists like to visit',
            image:require("../assets/places/market.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:"Temple Street is a street market that many tourists like to visit. It is close to the attractions that draw tourists by the millions to the Tsim Sha Tsui area each year. People look for street bargains or to have some inexpensive Chinese food. The Temple Street Night Market is one of Hong Kong's tourist shopping highlights. We have put together this Temple Street information page and a simple touring plan to help you understand the street and know how to take advantage of the street optimally for a couple of hours for shopping, dining and having a good time during your visit to Tsim Sha Tsui.",
        },
        {
            userid: "user1",
            exploreid: 9,
            title:"Ce-La-Vi",
            subtitle:'CÉ LA VI Hong Kong is a large place, spanning over three floors above the popular nigthlife area Lan Kwai Fong in Hong Kong Central',
            image:require("../assets/places/celavi.jpg"),
            //tags:"Chinese",
            //price: "$$$",
            //cost:100,
            value:1,
            details:'CÉ LA VI Hong Kong is a large place, spanning over three floors above the popular nigthlife area Lan Kwai Fong in Hong Kong Central. Up here you find both a modern Japanese-inspired indoor restaurant, along with Club Lounge and rooftop bar, named Sky Deck. The Sky Deck terrace had a refurbishment during summer 2018 for the CÉ LA VI 3rd anniversary, and is now even more stylish then before. Modern and sleek, with details in brushed copper and lots of comfy lounge sofas. The view is however exactly the same, with sweeping 270-degree views of the Hong Kong skyline, the surrounding mountains and Victoria Harbor. Apart from the grand views, the CÉ LA VI rooftop bar is alot about atmosphere.',
        },
    ]

    Orders =[

    ]

    purchase = [

    ]

    cards=[
            {
                userid: "user1",
                listingid:1,
                title:"Jen Ju Dan",
                subtitle:"The attention to detail is what makes Jen Ju Dan appealing to bubble tea lovers",
                image:require("../assets/food/JJD/JJD.jpg"),
            },
            {
                userid: "user1",
                listingid:2,
                title:"Mira",
                subtitle:"Walking into The Mira’s minimalist lobby feels like entering another galaxy",
                image:require("../assets/stay/Mira/Mira1.jpg"),
            },
            {
                userid: "user1",
                listingid:3,
                title:"Honeymoon",
                subtitle:"Durian addicts get their fix here with Honeymoon's famous durian2",
                image:require("../assets/food/Honeymoon/Honeymoon.jpg"),
            },
            {
                userid: "user1",
                bookid:4,
                title:"Fairwood",
                subtitle:"Fairwood is one of Hong Kong’s most popular fast food restaurant chains",
                image:require("../assets/food/Fairwood/Fairwood.jpg"),
            },
            {
                userid: "user1",
                listingid:5,
                title:"Hop Yik Ta",
                subtitle:"Michelin recommended local restaurant in Sham Shui Po that specialises in cheong fun.2",
                image:require("../assets/food/HYT/HYT.jpg"),
            },
            {
                userid: "user2",
                listingid:6,
                title:"Crown Super Deluxe",
                subtitle:"This 60s Tokyo-inspired teppanyaki features three teppan grills in which diners can sit around and enjoy watching chefs grilling away.",
                image:require("../assets/food/CSD/CSD.jpg"),
            },
            {
                userid: "user2",
                bookid:7,
                title:"Fukuro",
                subtitle:"This modern izakaya is helmed by chef Shun Sato, a Sendai native who has worked in Tokyo’s famous Tsukiji Market",
                image:require("../assets/food/Fukuro/Fukuro.jpg"),
            },
            {
                userid: "user2",
                listingid:1,
                title:"Cafe De Coral",
                subtitle:"Cafe de Coral is a fast food restuarant",
                image:require("../assets/food/Cafe/Cafe.jpg"),
            },
            {
                userid: "user3",
                listingid:8,
                title:"Langham",
                subtitle:"The dining options at The Langham are so good that you’ll likely never want to leave.  ",
                image:require("../assets/stay/Langham/Langham1.jpg"),
            },
            {
                userid: "user3",
                listingid:3,
                title:"CHAAT",
                subtitle:"Helmed by chef Manav Tuli, previously head chef of Michelin-starred Tamarind in London",
                image:require("../assets/food/CHAAT/CHAAT.jpg")
            },

    ]


    //if variable that stores login is null make new
    static getInstance (){ 
        if (DataManager.myInstance == null) {
            DataManager.myInstance = new DataManager();
        }
        return this.myInstance;
    }

    getOrderSize(){
        return this.Orders.length;
    }
    getOrdersID(uid){
        return this.Orders.filter((rest) => rest.userID === uid)
    }

    getPurchaseID(uid){
        return this.purchase.filter((rest) => rest.userID === uid)
    }
    getPurchaseSize(){
        return this.purchase.length;
    }
    getOrders(){
        return this.Orders;
    }
    addOrder(order){
        this.Orders.push(order);
    }

    addPurchase(Purchase){
        this.purchase.push(Purchase);
    }

    changeData(newOrder){
        this.Orders = newOrder;
    }

    changeCards(newOrder){
        this.cards = newOrder;
    }
    getAirbnbID(ids){
        return this.Airbnb.filter((rest) => rest.id === ids)
    }
    getRestuarantsNum(ids){
        return this.Restuarants.filter((rest) => rest.restuarantsid === ids)
    }
    
    getUserID(){
        return this.userID;
    }
    
    getUserImage(ids){
        return this.users.filter((rest) => rest.id === ids);
    }

    getScreenID(){
        return this.screenID;
    }

    setUserID(id){
        this.userID = id;
    }
    setScreenID(id){
        this.screenID = id;
    }

    //returns the history of the particular user
    getmyHistory(id){
        return this.myHistory.filter((history) => history.userid === id)
    }

    //grabs restuarants 
    getRestuarants(){
        return this.Restuarants;
    }

    //returns each restuarant dependent on the tags
    getRestuarantsID(id){
        return this.Restuarants.filter((rest) => rest.tags === id)
    }

    getTab(){
        return this.Tab;
    }

    getTagsID(id){
        return this.tags.filter((filter) => rest.tags === id)
    }

    getPlaces(){
        return this.Hotels;
    }
    getPlacesID(ids){
        return this.Hotels.filter((rest) => rest.id === ids)
    }

    getCards(id){
        return this.cards.filter((card)=> card.userid === id);
    }


    }